### ISSUE TITLE
Feedback on trying it out

### ISSUE THREAD

**Issue by Stvad** [signalnerve/roam-backup#1]
First - This is awesome! Join us on the #hacking channel in Roam slack!

Some edges:
* I needed to manually enable actions on the fork (apparently disabled for forks)
* Nothing happened until I've made a commit
* S3 policy should probably really only have the `PutObject` permission for the bucket and not S3 Full access
* It actually timed out for me just now, but WF reports success =\ (gonna try increasing timeouts)

Requests:
* Also backup Markdown

**Comment by Stvad** [comment]
Also it does not seem to be able to handle the case when you have multiple databases (in that case you'd see their list after login). 's probably why this times out for me

**Comment by kristianfreeman** [comment]
hey @Stvad, this is great feedback, thanks so much! can you tell me more about the multi database thing? i was unaware you could even do that, how do you set it up?

**Comment by kristianfreeman** [comment]
some good docs stuff here, too - i'll update the README w/ the s2 perms stuff, and let ppl know you need to enable actions. 

should be able to make the markdown/json thing configurable too

**Comment by Stvad** [comment]
If you go to https://roamresearch.com/#/secretinvite you can create multiple databases on the same account. A relevant feature request would be to back up all of them :)

**Comment by Stvad** [comment]
Just run it in the dev env and confirmed that it times out on the DB selection page

**Comment by Stvad** [comment]
Moving multi-db discussion in #4

**Comment by sansari** [comment]
+1 on @Stvad's points regarding needing to enable actions, and make an initial commit. I was also able to confirm it still works when using a more conservative access policy, but that requires creating a custom policy.

Added some PRs to update README clarifying all of the above.

**Comment by Stvad** [comment]
One other thing is - I'd like the workflow to fail if one of the steps fails (so I can see when it's having problems)

**Comment by Stvad** [comment]
Also for my larger database the switch to JSON format does not seem to work =\

**Comment by kristianfreeman** [comment]
@Stvad I'm going to close this issue – #4 covers the multi-database work and @sansari has been a huge help in #3 #5 to get these things documented in the README. Feel free to re-open if you think there's something I missed!
